spring:
  profiles:
    active:
      - prod
      
  redis:
    database: 13
    host: 10.0.54.87
    port: 6379
    password: HaiMan2017
    timeout: 0
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  cache:
    redis:
      time-to-live: 86400 # 86400 seconds equals a day
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
    properties:
      # Configure Main Scheduler Properties
      org.quartz.scheduler.instanceName: cloud-portal-scheduler
      org.quartz.scheduler.instanceId: AUTO # 如果使用集群，instanceId必须唯一，设置成AUTO
      org.quartz.scheduler.skipUpdateCheck: true
      # Configure ThreadPool
      org.quartz.threadPool.class: org.quartz.simpl.SimpleThreadPool
      org.quartz.threadPool.threadCount: 10
      org.quartz.threadPool.threadPriority: 5
      # Configure JobStore
      org.quartz.jobStore.misfireThreshold: 60000
      org.quartz.jobStore.class: org.quartz.impl.jdbcjobstore.JobStoreTX # 存储方式为数据库
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
      org.quartz.jobStore.useProperties: true # 使用自己的配置文件
      org.quartz.jobStore.tablePrefix: T_QRTZ_
      org.quartz.jobStore.isClustered: false # 是否使用集群

logging:
  config: classpath:logback.xml
  
project:
  base:
    repository:
      provider: com.moraydata.general.management.repository.BaseMultielementRepositoryFactory
      batch:
        size: 30
    wechat:
      service: # 支持微信服务号
        appId: wx7a2ffdf99b8bd18c # wx7a2ffdf99b8bd18c 公司账号 wx1fb4cf9f5f3385e7 测试账号
        appSecret: 7332143e8d281cc7588e510ae615cea5 #  7332143e8d281cc7588e510ae615cea5 公司密码 3889e726e00f19662e8b7e9cde4b5599 测试账号
        accessTokenUrl: https://api.weixin.qq.com/cgi-bin/token # 获取access_token的url
        ticketUrl: https://api.weixin.qq.com/cgi-bin/qrcode/create # 创建二维码ticket的url
        showQRCodeUrl: https://mp.weixin.qq.com/cgi-bin/showqrcode # 显示二维码的url
        createMenuUrl: https://api.weixin.qq.com/cgi-bin/menu/create # 创建服务号菜单的url
        connectOAuth2Menu4CodeUrl: https://open.weixin.qq.com/connect/oauth2/authorize # 创建每个菜单按钮携带重定向url并获取code所需的url
        snsOAuth2TokenAndOpenIdUrl: https://api.weixin.qq.com/sns/oauth2/access_token # 服务号菜单跳转通过code使用OAuth2方式获取access_token和openid的url
        sendTemplateMessageUrl: https://api.weixin.qq.com/cgi-bin/message/template/send # 发送模板消息所用的url
        templateMessage:
          publicSentiment: 259crn-Levvu-2VDe2jff43bHncbzyQC3LWCTpZCWBw # 推送舆情异常消息的模板Id
    business:
      publicSentiment:
        interfaceUrl: http://47.93.59.158:18882/wxNotice/
    rest:
      connection:
        connectionTimeout: 5000
        readTimeout: 5000